language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci
  - PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - pnpm install
  - pnpm run build
script:
  - nohup npm start &
  - sleep 5
  - npm run test
